# Generated by Django 4.2.6 on 2023-10-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(default=1, upload_to='thumbs/'),
            preserve_default=False,
        ),
    ]
